use proxy env if available
flystack/misty pull request #15
Opened 2017-03-28 11:41 UTC by hgw77

for some reason Net::HTTP did not recognizes the http_proxy ENV variable, so I added an if case to use http_proxy if available

2017-03-28 11:46 UTC, Carthaca commented
lgtm

2017-04-12 01:48 UTC, gildub requested changes
Sorry for long delay, I was on leave!
👍 for adding this.

Please review comments.

2017-04-12 01:48 UTC, gildub commented on lib/misty/http/net_http.rb
> +end
Could you please restore the newline at end of file?

2017-04-12 01:57 UTC, gildub commented on lib/misty/http/net_http.rb
>          http = Net::HTTP.new(uri.host, uri.port)
What about having a else case for the default http?

2017-04-12 07:36 UTC, hgw77 commented on lib/misty/http/net_http.rb
>          http = Net::HTTP.new(uri.host, uri.port)
I am not sure that makes sense because you have to declare in any case the http variable outside the if/else block

2017-04-12 08:02 UTC, hgw77 commented
I messed something up and will redo my pull request

2017-04-12 08:02 UTC, closed without merging