decrease minimum required version for json gem to 1.8.3
flystack/misty pull request #21
Opened 2017-04-12 09:01 UTC by majewsky

ActiveSupport for Rails 4 requires `json ~> 1.7 >= 1.7.7` which is
incompatible with Misty's previous requirement of `json ~> 2.0`. To be
able to use Misty with an existing Rails 4 application, we verified that
the unit tests pass with version 1.8.3 of the json gem (which is the
last version before 2.0).

According to the [release notes for the json gem][1], the only
backwards-incompatible change in 2.0 was to drop support for older
Rubies, so this should not break anything in practice.

[1]: https://github.com/flori/json/blob/master/CHANGES.md

2017-04-13 06:27 UTC, gildub requested changes
+1 for supporting Rails 4 which is still active.

BTW, which version of Rails 4.x are you testing against?

2017-04-13 06:27 UTC, gildub commented on misty.gemspec
> +  spec.add_dependency 'json', '>= 1.8.3', '< 3'
It seems better to use Ruby's Pessimistic Operator [1] instead to declare deps [2].

Could you please try first:
`spec.add_dependency 'json', '~> 1.8'`

Or if that's not enough then:
`spec.add_dependency 'json', '~> 1.8', '>= 1.8.3'`


[1] https://robots.thoughtbot.com/rubys-pessimistic-operator
[2] http://guides.rubygems.org/patterns/#declaring-dependencies

2017-04-13 06:54 UTC, hgw77 commented on misty.gemspec
> +  spec.add_dependency 'json', '>= 1.8.3', '< 3'
Rails version is 4.2.4 if you are intereseted you can take a look [here](https://github.com/sapcc/elektra)

2017-04-13 09:06 UTC, majewsky commented on misty.gemspec
> +  spec.add_dependency 'json', '>= 1.8.3', '< 3'
The pessimistic operator is not the same. WIth `~> 1.8`, versions 2.x would not be allowed any more, thus potentially breaking existing users that need `json >= 2.0`, and potentially prohibiting us too from moving to a newer json gem when we update Rails next time.

2017-04-13 09:53 UTC, gildub commented on misty.gemspec
> +  spec.add_dependency 'json', '>= 1.8.3', '< 3'
You're right, so we need '>= 1.8.3' but why '< 3'?

2017-04-13 10:10 UTC, gildub approved these changes

2017-04-13 10:52 UTC, majewsky commented on misty.gemspec
> +  spec.add_dependency 'json', '>= 1.8.3', '< 3'
`< 3` is in fact not a change. The previous `~> 2.0` is a shorthand for `>= 2.0, < 3`. I just decreased the minimum requirement; the upper bound stays the same.

2017-04-18 06:32 UTC, gildub commented on misty.gemspec
> +  spec.add_dependency 'json', '>= 1.8.3', '< 3'
Got it, thank!

2017-04-18 06:32 UTC, merged